In [4]:
import numpy as np

In [5]:
np.__version__

'2.3.5'

In [6]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:11:29) [Clang 20.1.8 ]'

In [7]:
my_list = ["ram",30,55000]
my_list

['ram', 30, 55000]

In [8]:
arr = np.array(my_list)
type(arr)

numpy.ndarray

In [9]:
arr.shape

(3,)

In [10]:
# np. we learn important functions


In [11]:
# retrun even space
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5.)

array([0., 1., 2., 3., 4.])

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10) 

array([], dtype=int64)

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [18]:
np.zeros(10) # parametere tuning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros(10,dtype=int) # hyper parameter tuning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# how to print 2d array

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones(5) # parametere tuning 

array([1., 1., 1., 1., 1.])

In [24]:
np.ones(5,dtype=int) # hyperparameter tuning

array([1, 1, 1, 1, 1])

In [25]:
# Randon function 

In [26]:
rand(3,2)

NameError: name 'rand' is not defined

In [27]:
np.random.rand(3)

array([0.70168488, 0.19174637, 0.64890414])

In [28]:
np.random.rand(2,3) # rand fucntion always generate float

array([[0.47954523, 0.2084909 , 0.8947894 ],
       [0.78694113, 0.50582479, 0.51301014]])

In [30]:
# intergere only 
np.random.randint(2)

0

In [31]:
np.random.randint(1)

0

In [34]:
# randint() it generate int values of random 
np.random.randint(1,10,4) # generate a rabndom number 1 to 10 choose 4 as numbers

array([6, 3, 2, 2])

In [35]:
np.random.randint(10,20,(5,4))

array([[15, 13, 10, 14],
       [10, 14, 13, 17],
       [15, 18, 16, 10],
       [12, 18, 12, 19],
       [16, 14, 17, 15]])