In [27]:
import numpy as np

# 1) Array Creation functions

In [28]:
# create an array from  a list
arr = np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [29]:
# create an array with evenly spaced values
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [30]:
# create an array filled with zeros , 2*3 known as parameter tunning
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
# crteate an array filled with zeros known as hyper-parameter tuning
arr = np.zeros((2,3),dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

- create an identity matrix in diagonal there will be all one and left and right side 
- will be zeros


In [32]:
diagonal_array = np.eye(4)
diagonal_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 2) Array Manipulation Functions

In [33]:
# reshape an array
arr = np.array([1,2,3,4])    
reshaped = arr.reshape(4,1)
reshaped

array([[1],
       [2],
       [3],
       [4]])

- flatten an array 

In [34]:
flatten_arr = np.arange(0,9).reshape(3,3,1)
flatten_arr

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [35]:
flatten_arr1 = np.ravel(flatten_arr)
print("Flattened array:", flatten_arr1) 

Flattened array: [0 1 2 3 4 5 6 7 8]


# Transpose an array 

In [36]:
e1 = np.array([[1, 2], [3, 4]])
e1

array([[1, 2],
       [3, 4]])

In [37]:
transpose_arr = np.transpose(e1) # row to coumns columns to row
transpose_arr

array([[1, 3],
       [2, 4]])

In [41]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.stack((a,b)))

print(np.stack((a,b), axis=1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [42]:
a1 = np.array([1,2])
a2 = np.array([2,4])
stacked = np.vstack([a2,a1])
print("stacked array:\n",stacked)

stacked array:
 [[2 4]
 [1 2]]


In [43]:
stacked = np.hstack([a2,a1])
print("stacked array:\n",stacked)

stacked array:
 [2 4 1 2]


# 3) Mathematical Functions

In [45]:
# add two arrays also known as brodcasting 
arr = np.array([1,2,3,4,5])
add_arr =  np.add(arr,2)
add_arr

array([3, 4, 5, 6, 7])

In [47]:
# dot product
arr = np.array([1,2,3])
arr1 = np.array([2,3,1])
dot_product = np.dot(arr,arr1)
dot_product

np.int64(11)

In [49]:
# sqrt 
sqrt = np.sqrt(arr)
sqrt

array([1.        , 1.41421356, 1.73205081])

In [50]:
# power 
power = np.power(arr,2)
power

array([1, 4, 9])

# 4) Statistical Functions

In [52]:
# mean using np
s = np.array([1,2,3,4])
mean = np.mean(s)
mean

np.float64(2.5)

In [56]:
# variance of an array
var =np.var(s)
var

np.float64(1.25)

In [57]:
# standard deviation of an array 
std_dev = np.std(s)
std_dev

np.float64(1.118033988749895)

- Mean      = Sum of values / Number of values

- Variance  = Average of squared deviations from mean

- Std Dev   = √Variance

- Median    = Middle value after sorting

In [58]:
median = np.median(s)
median

np.float64(2.5)

- A.T                      # transpose
- A @ B                    # matrix multiplication
- np.linalg.det(A)         # determinant
- np.linalg.inv(A)         # inverse
- np.linalg.solve(A,B)     # solve AX=B
- np.linalg.eig(A)         # eigen values/vectors
- np.linalg.matrix_rank(A) # rank
- np.linalg.norm(A)        # norm
- np.linalg.svd(A)         # SVD

- det     → Matrix invertible or not
- inv     → Matrix inverse
- eig     → PCA, ML
- solve   → AX = B
- norm    → Distance/Magnitude
- svd     → Dimensionality reduction
- rank    → Number of independent rows/columns

# 6) Random Sampling Functions

In [80]:
arr = np.random.rand(3)   # random 0 to 1
arr

array([0.43016015, 0.35871023, 0.36767064])

In [83]:
np.random.seed(0)  # this will freeze the random numbers
arr = np.random.rand(3)   # random 0 to 1
arr

array([0.5488135 , 0.71518937, 0.60276338])

In [85]:
# generate random interger 
arr = np.random.randint(0,10,size=5)
arr

array([3, 7, 9, 3, 5])

In [87]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# 7) Boolean & Logical Functions

In [91]:
logical_arr = np.array([True,False,True])
all_true = np.all(logical_arr)  # check all elements are true 
print("all elements are true\n",all_true)

all elements are true
 False


In [92]:
logical_arr = np.array([True,True,True])
all_true = np.all(logical_arr) # check all elements are true 
print("all elements are true\n",all_true)

all elements are true
 True


In [94]:
# check if any elemets are true
logical_arr = np.array([True,True,True])
all_true = np.any(logical_arr) # check any elemets are true 
print("all elements are true\n",all_true)

all elements are true
 True


# 8) Set Operations

In [100]:
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,5])
intersection = np.intersect1d(set_a,set_b)
intersection

array([3, 4])

In [101]:
union_of_array =np.union1d(set_a,set_b)
print("union of 1d array\n",union_of_array)

union of 1d array
 [1 2 3 4 5]


# 9) Array Attribute Functions

In [106]:
a = np.array([1,2,3,4])
# shape of an array 
shape = a.shape
size = a.size
dimensions = a.ndim 
dtype = a.dtype

print("shape of an array:",shape)
print("Number of elements of an array:",size)
print("number of dimensions of array:",dimensions)
print("data type of an array:",dtype)

shape of an array: (4,)
Number of elements of an array: 4
number of dimensions of array: 1
data type of an array: int64


# 10) Other Functions

- Create a copy of an array

In [107]:
a

array([1, 2, 3, 4])

In [109]:
copied_array = np.copy(a)
print("copied array:",copied_array)

copied array: [1 2 3 4]


In [110]:
a[0] = 4
a

array([4, 2, 3, 4])

In [111]:
copied_array

array([1, 2, 3, 4])

In [112]:
id(copied_array)

6002551920

In [113]:
id(a)

6002550672

In [114]:
# check if two array shared memorey 
shared = np.shares_memory(a,copied_array)
shared

False