# what is numpy 
- numpy is python library that provides mutidimensional array object
- meaning
- Scientific Computing in python 

- "The core object of NumPy is ndarray, which stands for n-dimensional array. It stores data in one or more dimensions and generally requires homogeneous data types. Because the data is stored contiguously in memory, NumPy operations are much faster and more memory efficient than Python lists."

# Creating Numpy Array

In [2]:
import numpy as np 

In [3]:
np.array([1,2,3,4,5]) #1D array

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array([2,4,6,8])  # Vector
arr

array([2, 4, 6, 8])

In [5]:
type(arr)

numpy.ndarray

- to get shape of array using numpy we need to use shape attribute

In [6]:
arr.shape

(4,)

# 2D Array OR (Matrix)

In [7]:
mat_arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
mat_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
type(mat_arr)

numpy.ndarray

In [9]:
mat_arr.shape

(2, 5)

# 3D Array Or (Tensor)

In [10]:
tensor_arr = np.array([[1,2,3],[4,5,6,],[7,8,9],[10,11,12]])
tensor_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
type(tensor_arr)

numpy.ndarray

In [12]:
tensor_arr.shape

(4, 3)

# dtype Meaning

- dtype = Data Type
- "What type of values should I store?"
- int
- float
- str
- bool
- complex


- You can explicitly tell NumPy the datatype.

- If not given, then the type will be determined automatically. by numpy

In [13]:
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [14]:
np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

In [15]:
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

# Numpy Arrays Vs Python Sequences
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically).
Changing the size of an ndarray will create a new array and delete the original.

Used Everywhere in Data Science

Libraries internally convert data into NumPy arrays.

Examples:

Pandas
Scikit-Learn
OpenCV
TensorFlow
Matplotlib

# Array Attributes

In [16]:
# arange arange an array # 1d array
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [17]:
# reshape will shape to any diminetion array
# [1,2,3,4,5,6,7,8,9]
# reshape(row * columns) = 9
# 1*9
# 3*3
# 9*1
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# ones & zeroes
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# random will genrate random numbers
np.random.random((3,3))

array([[0.84584966, 0.1043026 , 0.48524488],
       [0.40094121, 0.81071962, 0.78971871],
       [0.33746049, 0.52892691, 0.64898458]])

In [21]:
# linspace method 
# It is also called as Linearly space ,
# Linearly separable,
# in a given range at equal distance it creates points.
# linspace(start, stop, num_points)
# Start from -5
# End at 5
# Create TOTAL 4 points
# All points should be equally spaced.
np.linspace(-5,5,4)

array([-5.        , -1.66666667,  1.66666667,  5.        ])

- identity

- dentity Matrix (I)

An identity matrix is a square matrix in which:

All diagonal elements are 1
All other elements are 0

- 3 × 3 Identity Matrix
- [1 0 0]
- [0 1 0]
- [0 0 1]

In [22]:
# create the identity matrix

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Array Attributes

In [25]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [26]:
arr2 = np.arange(12,dtype=float).reshape(4,3)  #2d matrix
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [27]:
arr3 = np.arange(8,dtype=int).reshape(2,2,2) #3d matrix
arr3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim 
- to find the given number of dimentions

In [28]:
arr.ndim

1

In [29]:
arr2.ndim

2

In [30]:
arr3.ndim

3

# shape
- it givens the items how many number of rows and columns present

In [31]:
arr.shape

(5,)

In [32]:
arr2.shape

(4, 3)

In [33]:
arr3.shape

(2, 2, 2)

# Size
- gives number of items

In [34]:
arr.size
print(arr,'==>',arr.size)

[0 1 2 3 4] ==> 5


In [35]:
arr2.size
print(arr2,'==>',arr2.size)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]] ==> 12


In [36]:
print(arr3,'==>',arr3.size)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] ==> 8


# item size
- Memory occupied by the items

In [37]:
arr.itemsize # bytes

8

In [38]:
arr2.itemsize # integer 64 gives = 8 bytes

8

In [39]:
arr3.itemsize # integer 32 gives = 4 bytes

8

# dtype
- provides data type of the items

In [40]:
print(arr.dtype)

int64


In [41]:
print(arr2.dtype)

float64


# Changing Data Type

- astype

In [42]:
arr

array([0, 1, 2, 3, 4])

In [43]:
arr.astype(float)

array([0., 1., 2., 3., 4.])

# Scalar Operations

- scalar operations on numpy array includes performing
- addition , subtraction , multiplication
- on each elements of numpy array

In [44]:
# arithimetic
arr

array([0, 1, 2, 3, 4])

In [45]:
arr + 1

array([1, 2, 3, 4, 5])

In [46]:
# subtraction 
arr - 1

array([-1,  0,  1,  2,  3])

In [47]:
# Multiplication 
arr * 2

array([0, 2, 4, 6, 8])

In [48]:
# power
arr**2

array([ 0,  1,  4,  9, 16])

In [49]:
# modulos it gives remainder
arr%2

array([0, 1, 0, 1, 0])

In [50]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [51]:
arr//2

array([0, 0, 1, 1, 2])

# relational operators

- the relational operators are also known as comparison operators
- their main function is to return a true or false based on the value of operands

In [52]:
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [53]:
arr2 > 3 # if 3 is greater then everything then return true

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [54]:
arr2 > 20

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

# vector operations

In [55]:
z1 = np.arange(9).reshape(3,3)
z2 = np.arange(9).reshape(3,3)

In [56]:
z1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
z2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
# to conact we must have same dimiention 
z1 + z2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [59]:
z1 * z2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [60]:
z1/z2

/var/folders/vc/w3_sxb6x2g16jqk905nfn07h0000gn/T/ipykernel_33160/3535024290.py:1: RuntimeWarning: invalid value encountered in divide
  z1/z2


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [61]:
z1//z2

/var/folders/vc/w3_sxb6x2g16jqk905nfn07h0000gn/T/ipykernel_33160/314679153.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  z1//z2


array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])