In [1]:
import numpy as np 

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys 
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:11:29) [Clang 20.1.8 ]'

# creating list and converting to an array 

In [4]:
l = ['test',1,1.2,1+2j]

In [5]:
type(l)

list

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [8]:
np.arange(0,30,5,dtype=int)

array([ 0,  5, 10, 15, 20, 25])

In [9]:
# parameter tuning
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# hyper parameter tuning
np.zeros(5,dtype=float)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones(2)

array([1., 1.])

In [12]:
np.ones((2,2))  # (row,columns)

array([[1., 1.],
       [1., 1.]])

In [13]:
n = (6,7)
type(n)

tuple

In [14]:
n1 =(6,8)
type(n1)

tuple

In [15]:
# parameter tuning 
np.zeros(n1)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
# hyperparameter tuning
np.zeros(n,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [17]:
range(5)

range(0, 5)

In [18]:
list(range(5))

[0, 1, 2, 3, 4]

In [19]:
np.random.rand(2,3)  

array([[0.64801173, 0.20339384, 0.51626907],
       [0.19409919, 0.88169005, 0.9172818 ]])

In [20]:
# we can give low and high
np.random.randint(2,10)  

2

In [30]:
np.random.randint(2,10,5)  # how many numbers we need otp 5

array([3, 5, 7, 4, 9])

In [31]:
np.random.randint(30,20,10)

ValueError: low >= high

In [32]:
np.random.randint(-30,30,10)

array([ 19,   4, -30,  17,  16,  -8,  27,  24,  24, -23])

In [39]:
np.random.randint(5,9)

5

In [40]:
#generre the element 10 -30 with 4*4 mtri
np.random.randint(-30,10,(4,4))

array([[ -5, -29,   5, -30],
       [ -6,   1,   4,  -2],
       [  7,   5,   4, -18],
       [-18, -13, -21, -29]])

In [41]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# slicing in matrix 

In [43]:
# slicing in matrix 
b = np.random.randint(10,20,(4,4))
b

array([[19, 14, 11, 19],
       [11, 18, 16, 14],
       [17, 14, 19, 11],
       [11, 18, 11, 14]])

In [44]:
type(b)

numpy.ndarray

In [45]:
b[:]

array([[19, 14, 11, 19],
       [11, 18, 16, 14],
       [17, 14, 19, 11],
       [11, 18, 11, 14]])

In [50]:
b[1:3,1:3]   # (row,column,step)

array([[18, 16],
       [14, 19]])

# Operations

In [52]:
a = np.random.randint(10,20,10)
a

array([11, 15, 19, 11, 16, 19, 16, 13, 16, 16])

In [53]:
id(a)

5241560432

In [57]:
arr = np.random.randint(0,100,(4,4))

In [58]:
arr

array([[33, 71,  7, 14],
       [42, 46, 99, 34],
       [41, 67, 39, 72],
       [53, 26,  6, 21]])

In [64]:
arr[:]

array([[33, 71,  7, 14],
       [42, 46, 99, 34],
       [41, 67, 39, 72],
       [53, 26,  6, 21]])

In [71]:
arr[:4]

array([[33, 71,  7, 14],
       [42, 46, 99, 34],
       [41, 67, 39, 72],
       [53, 26,  6, 21]])

In [74]:
arr[1,3] # row 1 first row column of 3

np.int64(34)

In [79]:
arr[-4,3]

np.int64(14)

In [80]:
arr[-1,-2]

np.int64(6)

In [82]:
arr[::-1] # it will reverse the array

array([[53, 26,  6, 21],
       [41, 67, 39, 72],
       [42, 46, 99, 34],
       [33, 71,  7, 14]])

In [83]:
arr[:-3]

array([[33, 71,  7, 14]])

In [84]:
arr

array([[33, 71,  7, 14],
       [42, 46, 99, 34],
       [41, 67, 39, 72],
       [53, 26,  6, 21]])

In [85]:
arr.max()

np.int64(99)

In [86]:
arr.min()

np.int64(6)

In [87]:
arr.mean()

np.float64(41.9375)

In [91]:
np.median(arr)

np.float64(40.0)

In [95]:
arr.reshape(2, 8)

array([[33, 71,  7, 14, 42, 46, 99, 34],
       [41, 67, 39, 72, 53, 26,  6, 21]])

In [98]:
arr.reshape(2, 8,order='F')

array([[33, 41, 71, 67,  7, 39, 14, 72],
       [42, 53, 46, 26, 99,  6, 34, 21]])

In [97]:
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [101]:
# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  F type array:")
for num_array in np.nditer(num_array, order="F"):  # coulumn wise print
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  F type array:
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 1 6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96 2 7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97 3 8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93 98 4 9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99 

# Indexing

In [102]:
mat = np.arange(0,100).reshape(10,10)

In [103]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [104]:
mat[4,5]

np.int64(45)

In [106]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [107]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [108]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [110]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# masking we also called as filter

In [111]:
id(mat)

5349615984

In [112]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [114]:
mat[mat==50]

array([50])

In [115]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [116]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [117]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [118]:
mat[mat==50]

array([50])

In [126]:
# python programe to generate opt
import random
def generate_otp(length=4):
    """Generate a numeric OTP of a specified length"""
    digit ='012345'
    otp = ''.join(random.choice(digit) for _ in range(length))
    return otp
otp_length = 4 
generate_otp(otp_length)

'1233'